### ISSUE TITLE
Langflow run command not working as static_files_dir error

### ISSUE THREAD

**Issue by mirzasreza** [langflow-ai/langflow#1534]
![Screenshot 2024-03-16 092833](https://github.com/logspace-ai/langflow/assets/8491236/aee2e59c-dbcd-40fc-bdd0-90fe89825b61)
I have cloned zustand/io/migration branch.
I am getting this error while i run langflow run after poetry install.
 
RuntimeError: Static files directory /mnt/d/build/wLang/langflow7/src/backend/langflow/frontend does not exist.
basically, the program generating wrong static_files_dir

**Comment by mirzasreza** [comment]
@dosubot i copied frontend folder to specified location it was looking. But when I run and open browser it shows me blank.

**Comment by ogabrielluiz** [comment]
Hi @mirzasreza 
How are you?

It seems you are running `langflow run` from the repo. This shouldn't work because the backend requires a built version of the frontend to work. 

One way you could do that is just running `make backend` in a terminal and `make frontend` in another. 

Another way would be to run `make build_frontend` and  then `langflow run --path src/backend/langflow/frontend` 

Another would be to just run `make build_and_run` or `make build_and_install` which would work like as if you ran `pip install langflow` but using the local code.
