### ISSUE TITLE
How to import code from local modules into customcomponent file?

### ISSUE THREAD

**Issue by arose26** [langflow-ai/langflow#1634]
In creating custom components I wish to separate different helper functions of the code into files outside the CustomComponent derived class file. However, when I try to import another module into a customcomponent file, I get the error saying that the code cannot be found. This happens whether the module is in a subdirectory (e.g. helpers/codemodule.py) or just in the same directory as the component itself.
What is the practice for separating code in a CustomComponent? The documentation is lacking on this.

**Comment by arose26** [comment]
The import syntax works from a regular python file, but not from inside a CustomComponent. This is a problem specific to creating custom components. The error I get back is the following:
`\site-packages\\langflow\\utils\\validate.py", line 204, in
                             prepare_global_scope\n    raise ModuleNotFoundError(f"Module {node.module} not
                             found. Please install it and try again.") from e\nModuleNotFoundError: Module
                             helpers.custom_helpers not found. Please install it and try again.\n'}`

**Comment by yamonkjd** [comment]
I couldn't understand your question well, but I hope this helps. Try declaring the module you want to import at the beginning of the build method of the custom component. In LangFlow, it seems to operate with the feeling of copying the code of the build method and building it anew.

**Comment by yamonkjd** [comment]
Ah, you're talking about the new module of Langflow. My response was useless.

**Comment by arose26** [comment]
What I ended up doing was put my module of helper functions into the site-packages folder and now I can import it.  I'm not sure if this is the right practice but for now it works.

**Comment by ogabrielluiz** [comment]
Hey all 

I don't think this is a good practice but I think we can improve on that implementation. 

Generally, we add the path to the PYTHONPATH for this to work, but we don't do that in Langflow.

We could add that in a patch now and it should help you with that. 

What I'm thinking is adding your LANGFLOW_COMPONENTS_PATH to the `sys.path`. 

Now, if you want to make it so a different folder becomes accessible, then we need to think of other ways of doing that.

**Comment by yamonkjd** [comment]
As a suggestion for the beta version of the LangFlow project, how about introducing a plugin concept? 
I've been trying my best to understand the structure of LangFlow, but due to my limited capabilities, 
it's challenging to follow everything and thus difficult to rashly extend concepts like LangFlow's manager or service. 
Notably, the "helper" concept, which extends beyond the basic functions of LangChain to allow for user-customized expansions, resembles the plugin systems seen in platforms like Figma or AUTO GPT.

 Given that LangFlow already has a LangFlow Store implemented, it would be beneficial to add a system that differentiates and shares custom components and separate plugin components. Through this approach, users could select specific functionalities, such as timers and webhooks, according to their needs and install the necessary packages or modules, similar to NPM, at the directory level. This would not only reduce the overall size of the project but also make it more suitable for on-premise use.

To summarize, the proposal involves the addition of a plugin concept that is managed at the directory level, distinct from how custom components are currently placed in the `src` folder. Instead, a dedicated plugin folder would be established at the project root level, which the system would reference (with paths potentially provided via environment variables). 

This configuration isn't meant to complicate matters but to enable the system to accommodate functionalities like webhooks, timers, trigger calls, or integration with services like Selenium Hub at the flow's granular levels by system-level package inclusion. If implemented, this could allow for more nuanced control and customization within the flow, enhancing the platform's flexibility and capability to cater to specific user needs or project requirements.

**Comment by yamonkjd** [comment]
I believe LangFlow should actively benchmark against n8n, which incorporates a similar concept under the name "addons".
