### ISSUE TITLE
Error Building Component: Error building vertex OpenAI Embeddings: OpenAIEmbeddingsComponent.build() missing 1 required positional argument: 'openai_api_key'

### ISSUE THREAD

**Issue by ALee008** [langflow-ai/langflow#1690]
**Describe the bug**
First time using datastax. I used this [tutorial](https://pre-release.langflow.org/guides/rag-with-astradb#open-the-vector-store-rag-project) and created a "Vector Store RAG". I configured the Astra Tokens and API and created an OpenAI API Key. I followed the tutorial an pressed the "play" button. But I am getting the following error:

```
Error Building Component
- Error building vertex OpenAI Embeddings: OpenAIEmbeddingsComponent.build() missing 1 required positional argument: 'openai_api_key'
```
I went even as far as placing the OpenAI API Key in all components of the workflow - though this was not mentioned in the tutorial.

**Browser and Version**
 - Opera
 - Version 109.0.5097.45

**To Reproduce**
1. Go to 'New Project'
2. Click on 'Vector Store RAG'
3. Scroll down to the simple flow 'Ingestion Flow' (as suggested in the tutorial)
4. Provide valid Astra Token and Endpoint
5. Provide valid OpenAI_API_KEY
6. Click on "play" button in Astra DB component (as suggested in the tutorial)
7. Get message "Flow finisched successfully" and an error.

**Screenshots**
<img width="489" alt="image" src="https://github.com/langflow-ai/langflow/assets/39236016/231ef71b-f585-4481-af73-29dadc56c966">
<img width="1196" alt="image" src="https://github.com/langflow-ai/langflow/assets/39236016/dc7050cc-49a6-4d67-9bca-700a705b27ee">

**Comment by craigjurs** [comment]
Hello, I have the same issue.
![image](https://github.com/langflow-ai/langflow/assets/30636920/9e60fdaa-792b-4cef-8ecc-2f7c2b5049e1)

**Comment by craigjurs** [comment]
alright the problem is in the Build class

![image](https://github.com/langflow-ai/langflow/assets/30636920/abc112f6-c138-4cf5-949d-70279aba2f58)

this works, which is a hint

![image](https://github.com/langflow-ai/langflow/assets/30636920/61e0cfa5-e5c4-49eb-8ddd-42ed130dc154)

**Comment by ogabrielluiz** [comment]
Hey all

Are you using the HuggingFace Space when trying this? We remove all API keys there by default.

**Comment by sho5akimoto** [comment]
Hi All,
I also had the same issue at my duplicated HuggingFace Space env, and it looks like this issue is dupulicate of #1497 
I succeeded to create and run the Project based from "Vector Store RAG". Hope it will help you all.
1. Go to [Settings] page
2. Click [View] of 'LANGFLOW_REMOVE_API_KEYS' variable
3. Update the value from 'true' to 'false'
4. (I created 'OPENAI_API_KEY' variable, but maybe it's option)
5. Click [Factory rebuild] *Not sure it's necessary step. I wanted to run LangFlow with the updated 'LANGFLOW_REMOVE_API_KEYS' variable
6. Create the Project and try to do with the same steps which specified at https://pre-release.langflow.org/starter-projects/vector-store-rag
