### ISSUE TITLE
Backend/base pyproject missing vectorstore dependencies 

### ISSUE THREAD

**Issue by jordanrfrazier** [langflow-ai/langflow#1849]
**Describe the bug**

Overall question: 
What is the purpose of the dependency separation in `backend/base/langflow` - is it intended as an option for users to import minimal dependencies (w/o frontend) to run in their applications? Can you explain the usage and roadmap a bit further? 

Bug: 
The backend pulls in dependencies that are not included (even in extras): https://github.com/langflow-ai/langflow/blob/f9f1d9ba14735ef0adfab779a5ec692ad3aebe0e/src/backend/base/pyproject.toml#L26-L27

For example, if using a vector store component, all vector stores need to be installed to run. https://github.com/langflow-ai/langflow/blob/05cd6e4fd71866b6328ee669b7823def671c1a42/src/backend/base/langflow/components/vectorstores/__init__.py#L13

**Browser and Version**
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: (Langflow version 1.0.0a30)

**To Reproduce**

1. create env with backend deps
2. import a vector store component in a python file

**Comment by nicoloboschi** [comment]
@ogabrielluiz @anovazzi1 @lucaseduoli can you please provide more information here?

**Comment by ogabrielluiz** [comment]
Hey all

Sorry for the delayed response.

This is going to be improved over time but the idea is this:
If you want to have langflow with minimal dependencies and install your own to keep it more lightweight, you do so by installing `langflow-base`. The `langflow` package installs many more dependencies 

We plan on checking which components have their dependencies installed later on so that components that can't run, don't show up on the sidebar.

**Comment by jordanrfrazier** [comment]
Thanks Gabriel, that sounds good. I'll close for this knowing that those improvements are planned.
