### ISSUE TITLE
Cannot set a server for chroma db component because it no longer compiles due to chroma_server_cors_allow_origins value is not a valid list

### ISSUE THREAD

**Issue by vertgo** [langflow-ai/langflow#1882]
**Describe the bug**
When you use a chroma vector store with a locally running chroma instance (at 127.0.0.1:8000), the chroma component doesn't compile

**Browser and Version**
Safari Version 17.4 (19618.1.15.11.12)
this is using langflow vs 1.0.0.30a

**To Reproduce**
1. make an empty flow
2. add a chroma vector store
3. add an embedding (I used openai ada-2 and add an api key)
4. add a document (file loader->some random text document)
5. wire the file loader as the input of the chroma and the embedding as the embedding input of the chroma component
6. hit "Run" on the chroma component, watch it build with no problems7. 
8. go to "advanced" on chroma and set server host (I have tried "http://127.0.0.1", "127.0.0.1")
9. hit "run" on chroma and it says "Error building vertex Chroma: 2 validation errors for Settings chroma_server_cors_allow_origins none is not an allowed value (type=type_error.none.not_allowed) chroma_server_port extra fields not permitted (type=value_error.extra)"
10. Try a variety of cors allow lists: "*", ["*"], *, [*], etc
11. it still doesn't build

<img width="1482" alt="image" src="https://github.com/langflow-ai/langflow/assets/769494/cba54766-2d18-4592-b8de-dc20dde484c6">

**Comment by vertgo** [comment]
I used the exact list, and it still has the same error:
`["http://localhost:3000", "https://example.com"] `

**Comment by vertgo** [comment]
I have tried those values as well, and still the same error @dosu

**Comment by vertgo** [comment]
Actually, the bug is not in the cors list at all, but in changing the server.

To reproduce: 
1. Put in a new, working chroma component and supporting components (embeddings, documents)
2. Build component, it builds without error.
3. Set the CORS to ["\*"] or "\*", or anything you'd like
4. Build component, it builds without error
5. Set the server host to 127.0.0.1 (it was previously empty)
6. Build component, it NOW gives the error: chroma_server_cors_allow_origins value is not a valid list 
7. Delete the server host and return it to its original empty field
8. Build component, error remains!
9. Clear the CORS field as well.
10. Build, still error
@dosu

**Comment by SANHAJIFX** [comment]
Hi team,
I'm facing the same issue despite trying all the proposal above.

err:
Output
Error building vertex Chroma: 2 validation errors for Settings
chroma_server_cors_allow_origins
value is not a valid list (type=type_error.list)
chroma_server_port
extra fields not permitted (type=value_error.extra)

**Comment by coffeecodeconverter** [comment]
------------------------------------------
For Development / Test environments
------------------------------------------
Create SYSTEM environment variable name:
CHROMA_SERVER_CORS_ALLOW_ORIGINS

Set variable value (including the square brackets and double quotes):
["*"]

----------------------------------------
For Production / Live environments
---------------------------------------
Firstly, if the web developer tools console shows the below error, reporting the origin as "null":

Access to fetch at 'http://localhost:8000/api/v1/version' from origin 'null' has been blocked by CORS policy: 

This is when you're running the "index.html" web app as a file 
to resolve that, you need to host it as a web site on IIS if your native to windows, or NGinx, or WAMP, etc - "some" web server. 
it just needs to be served as a web site in order to communicate with the ChromaServer 

Secondly, once you've hosted the web app, but see this error instead:

Access to fetch at 'http://localhost:8000/api/v1/version' from origin 'http://localhost:80' has been blocked by CORS policy: 

You need to add "http://localhost:80" (or whatever your port is that you're hosting the web app on) 
to the CORS environment variable list like this, including the port used (including the square brackets and double quotes):
["http://localhost:80"]

if you have multiple ports, or hosts, then you write the environment variable value like this (including the square brackets):

["http://localhost:80", "http://localhost:5678", "http://192.168.100.10:6000", "http://192.168.100.20:6000"]

and remember to kill and restart ChromaServer in between any of these changes.

**Comment by emehmet** [comment]
Hi,

You may have installed chromadb globally with npm. Delete it and try again.

**Comment by anastasiosyal** [comment]
For future reference - Here's a simple docker compose file with the appropriate setting set to allow all


```
services:
  chroma:
    image: chromadb/chroma
    environment:
      - ALLOW_RESET=true
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    ports:
      - 8000:8000
    volumes:
      - ./chroma_data:/chroma/chroma_data

volumes:
  chroma_data: 
```
