### ISSUE TITLE
After adding Condition Router to a flow that has Text Input and Flow as Tool 2 components (not connected), the flow always crushes

### ISSUE THREAD

**Issue by grandua** [langflow-ai/langflow#2447]

**Comment by carlosrcoelho** [comment]
Hi @grandua Could you please provide more details about the error?

**Comment by carlosrcoelho** [comment]
@grandua, thanks a ton for reporting this issue. We really appreciate your effort in helping us make our project better.

Unfortunately, we couldn't make progress on fixing it because we need more details. So, we're gonna close this issue for now.

If you need help again or have more info to share, don't hesitate to open a new issue. We're always here to help!

Thanks for understanding and for your help.
