### ISSUE TITLE
使用本地代码运行出现RuntimeError报错请问如何解决

### ISSUE THREAD

**Issue by zzleaning** [langflow-ai/langflow#2451]
**Describe the bug**
使用本地代码运行出现一下报错
![1111](https://github.com/langflow-ai/langflow/assets/111033943/81aa951c-be3b-400e-8732-4800c78bbdb9)

RuntimeError: Static files directory D:\anaconda3\envs\first\lib\site-packages\langflow\frontend does not exist.
请问要如何解决

**Comment by nicoloboschi** [comment]
Please retry to install langflow using pip. It looks like you built it from the repository without generating the frontend files.

**Comment by xiaoxifei1223** [comment]
Hi, I know the reason for this because I’ve encountered this issue too.
This issue occurs because, in local code mode, using uv only sets up the Python backend environment and does not build the frontend.

You need to go into the source code directory src/frontend, then run npm install followed by npm run build

After a successful build, a build folder will be generated inside src/frontend. Copy the contents of this build folder (not the folder itself).

Then, create a new folder named frontend inside \src\backend\base\langflow, and paste the contents you copied from the build folder into this newly created frontend directory.

finally, return to the root dir, and uv run langflow run in the cmd.

这个问题的原因是如果仅仅按照repo 的说法，只是构建了backend 的环境，而不是完整的项目环境，你需要先进入到frontend 使用npm 进行build，获得build内容后，将其copy到\src\backend\base\langflow\frontend （frontend 文件夹需要新建）；
然后再uv run langflow run 启动
