### ISSUE TITLE
hackathon

### ISSUE THREAD

**Issue by nirvanahue** [langflow-ai/langflow#2690]
when i try to replace the openai component with the json file you uploaded in the hackathon it breaks the page completly and the massage shows restart lang flow or sendc error report

**Comment by carlosrcoelho** [comment]
Sorry for the late reply. The Hackathon is already over, but the error might have happened because you used the DataStax Langflow version first and then switched to the open-source version (pip) for a specific component or flow. This causes a version conflict since the DataStax version was way behind the current open-source version at that time.
