### ISSUE TITLE
Issue with Leading Zeros in Numeric Input for Create Data and Update Data Components

### ISSUE THREAD

**Issue by qiaolb** [langflow-ai/langflow#2702]
**Describe the bug**
While utilizing the `Create Data` and `Update Data` components for data encapsulation, I have encountered an issue where numeric values that begin with a zero are automatically stripped of their leading zeros. For instance, the number '`029`' is incorrectly transformed into '`29`'. This behavior is problematic as it can lead to data inconsistency and errors in applications that rely on the preservation of leading zeros for significance or formatting purposes.

**Browser and Version**
 - Edge, Chrome
 - Version: 1.0.7 - 1.0.9

**Comment by jordanrfrazier** [comment]
Hi @qiaolb, taking a look at this. Agreed that there are use cases where preserving the leading zero is significant. A couple thoughts:
* The current `Create Data` component does not allow the appropriate flexibility when defining the type of the schema. The `value` is automatically interpreted based on the content of the field, meaning that a value such as `001` is interpreted as an integer (and we "helpfully" strip those leading zeros, since `int(1)==int(001)`). 
  * We're improving this - a new type that can capture a user-defined schema is in the works. This will allow the user to define `001` as a `string`, preserving those leading zeros. 
* What if I want to store the value as an integer? Well, as you know, integers can't store leading zeros. However, there are strategies around storing additional metadata that track the number of leading zeros for each row. On gets, the db would need to know to retrieve the row as well as the metadata to lpad the integer on return. This would be a more involved path. 


So, hopefully your use case would allow the value to be stored as a string, which would preserve the leading zeros. I'll sync up with the team to see when we will allow that more flexible schema definition. If you'd like to share some specific use cases, it may help us finalize that work and ensure it fits what you need. Thanks!

**Comment by carlosrcoelho** [comment]
@qiaolb 

Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
