### ISSUE TITLE
ChatOpenAI gives error about specifying seed as model_kwargs

### ISSUE THREAD

**Issue by mieslep** [langflow-ai/langflow#2825]
### Bug Description

Using the OpenAI chat widget, I get an error:

```
ValidationError: 1 validation error for ChatOpenAI
__root__
Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of
`model_kwargs` parameter. (type=value_error)
```

The problem can be worked around by editing the widget code, in the `build_model(self)` function:

1. Comment out `model_kwargs["seed"] = seed` line
2. Add `seed=seed or 1,` to the `output = ChatOpenAI(` constructor

### Reproduction

Reproduces on 1.0.9 and 1.0.10.

1. Create a new project from Memory Chatbot
2. Set OpenAI API key
3. Run playground
4. Put in any message, error results.

### Expected behavior

no error.

### Operating System

Windows 11

### Langflow Version

1.0.9

### Python Version

- [ ] 3.12
- [X] 3.11
- [ ] 3.10

**Comment by ogabrielluiz** [comment]
Hey @mieslep 

Thanks for the heads up. 

This was fixed in #2779 and should be out in 1.0.11

**Comment by nicoloboschi** [comment]
This error could still happens if you use langchain_openai < 0.1.17. 
With Langflow 1.0.14, the langchain_openai dependency version is correct and there will not happen anymore. 
For previous installations, it's recommended to use langchain_openai 0.1.17 by running
```
pip install langchain_openai==0.1.17
```

See https://github.com/langchain-ai/langchain/pull/23691 for more reference

**Comment by aronweiler** [comment]
This is happening in `langchain-openai 0.1.20`, as well.
