### ISSUE TITLE
StoreImport-ComponentExecutionMismatch

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#2919]
### Bug Description

I am encountering a bug with components that I am sharing and importing from the store. Specifically, the same content does not run properly when imported from the store. However, copying and pasting the same code inside another custom component works as expected.

Video showing the problem: https://jam.dev/c/d6bdfede-6cb3-4bac-b12f-e9197c7682bd

### Reproduction

importing from the store
the same content does not run properly when imported from the store
However, copying and pasting the same code inside another custom component works as expected.

### Expected behavior

The flow or component should run regardless.

### Who can help?

@lucas

### Operating System

Ubuntu Linux

### Langflow Version

1.0.12

### Python Version

3.10

**Comment by lucaseduoli** [comment]
Looks like that is a problem with the Notify logic on the backend. With the Notify component, the backend reads the "Notify" name from the ID of the component and use a StateVertex class instead of an InterfaceVertex. Because you applied a custom code to the "Notify" component instead of a custom component, that causes it to have the StateVertex class and not work as expected. Applying the same code to the CustomComponent works, since the ID of the CustomComponent makes the backend use it as an InterfaceVertex.
@ogabrielluiz will transfer the logic of the StateVertex directly to the Notify and Listen components, then, the ID of the component will not matter and you can use the same component and it will work.
While that is being done, you can just use a CustomComponent with the same code and send it to the Store for the people to use.
