### ISSUE TITLE
"Store Message" duplicates human messages, but only on API call (not Playground)

### ISSUE THREAD

**Issue by mieslep** [langflow-ai/langflow#3028]
### Bug Description

When I invoke a flow using "Store Messages" components, I am getting duplicate Human messages in the database, but only when I invoke via API call. The database messages are correct when I invoke from the Playground.

### Reproduction

Reference flow https://raw.githubusercontent.com/AI-Phil/langflow-demo-flows/3b1afde4d590c5670e44417322dce580627353b1/flows/AstraMemoryChatbot.json 

Note this flow has implemented fix for https://github.com/langflow-ai/langflow/pull/3024 

when I invoke via Postman http://127.0.0.1:7861/api/v1/run/astra-memory-chatbot?stream=false

```
{"input_value": "what is my name?",
 "output_type": "chat",
 "input_type": "chat",
 "session_id": "1932f591-0a43-4546-8869-9f545503b5f3"
}
```

In both cases, there are two Langsmith entries: one for "OpenAI" and another for "Astra Memory Chatbot". I am not sure why there is not a single entry...

Versus when I invoke via the Playground, I have two different sorts of results. 

1. On the API invocation, the Human message is double-entered into the "Store Message"
2. The order in Langsmith is different: on the Playground entry, the "OpenAI" is logged first, and the "Astra Memory Chatbot" is logged second.  On the API call, the order is reversed.

### Expected behavior

1. There should be only one Human message in the database
2. There should be only one Langsmith entry for the invocation (maybe a separate issue?)

### Operating System

Windows 11

### Langflow Version

1.0.13

### Python Version

3.10

### Flow File

https://raw.githubusercontent.com/AI-Phil/langflow-demo-flows/3b1afde4d590c5670e44417322dce580627353b1/flows/AstraMemoryChatbot.json

**Comment by nicoloboschi** [comment]
Hey @mieslep for the duplicated messages, I sent out a fix in #3062 


For Langsmith, the duplicate comes from the fact that Langchain tracing is also enabled and the ChatOpenAI component is sending his own tracing.
Since the same key LANGCHAIN_API_KEY is used both by langflow and langchain, they both think they need to trace.
To demonstrate that, you can remove the variable LANGCHAIN_PROJECT.
Default project for langflow is "Langflow", for langchain is "default". You will see the traces going in different projects.

This can't be avoided currently. 

As follow up, I've created this issue for the wrong latencies #3064
