### ISSUE TITLE
File uploader in Advanced settings cannot be cleared. 

### ISSUE THREAD

**Issue by uladkaminski** [langflow-ai/langflow#3405]
### Bug Description

If you use file uploader in to Chat Input there is no way to clean the file. Removing show is keeping the file in the state.

### Reproduction

1) Add Chat Input to the flow
2) Select "Show" for "Files" in Advanced Settings.
3) Upload the file
4) No way to remove the file now

### Expected behaviour

Either additional button for removing file or unselecting show should clean the state of the node.

### Who can help?

@anovazzi1 

### Operating System

MacOS 14.5

### Langflow Version

1.0.15

### Python Version

3.11

### Screenshot

<img width="1286" alt="image" src="https://github.com/user-attachments/assets/5b62fa01-0678-495e-ac48-0a0b3b0db81c">

**Comment by Cristhianzl** [comment]
Hey @uladkaminski,

Thank you so much for your suggestion—it's very helpful!

I discussed it with my colleagues, and it turns out we're planning a refactor of the file uploader soon. This should significantly improve the user experience when uploading files to Flow.

I recommend holding off for this new feature—it's going to be worth the wait!

Thanks again!
