### ISSUE TITLE
Building takes for ever

### ISSUE THREAD

**Issue by mirzanejad** [langflow-ai/langflow#3447]
Hello, 

I am using LangFlow on Coolify using 2 vCPUs, 4096.00 MB, and 80 GB SSD on Ubuntu 24.04. The issue I have is that even the simplest flows take for ever to build. I am wondering what could be the issue? 

Thanks!

**Comment by italojohnny** [comment]
Hi, @mirzanejad . I hope you're doing well.

We're very interested in this type of issue since other users have reported similar problems, and it’s quite difficult to reproduce them.

I tried to emulate your issue using a container with the same CPU and RAM restrictions, but it worked fine for me.

Could you help us by enabling the log level to debug by setting the environment variable `LANGFLOW_LOG_LEVEL=debug` and providing us with the output when you notice this slowdown?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
