### ISSUE TITLE
Unexpected Deletion : sentence-transformers (remove api key from advanced and update HuggingFace components ( #3397))

### ISSUE THREAD

**Issue by Arron-Clague** [langflow-ai/langflow#3595]
### Bug Description

The old Hugging Space Component in v15 allows us to use Sentence-Transformers model locally : this seems to have been removed in v1.16/v1.17 ? Was this a mistake while executing  #3397 ? 

### Reproduction

Component (Hugging Space Embeddings) removed : remaining component (HuggingFace Embbeddings) (which I think was called (HuggingSpaceEnbeddings API) does not allow local embedding through sentence transformers.

### Expected behavior

Both local embeddings and API embeddings should be available. 

### Who can help?

@ogabrielluiz

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.01.16 , 1.0.17

### Python Version

3.10

**Comment by edwinjosechittilappilly** [comment]
Hi @Arron-Clague  Thanks for the feedback.
We no longer support local embeddings through Huggingface, due to some technical dependencies.
Meanwhile, if you like to try local embeddings please try Ollama Embeddings, which does provide most of the local embeddings model in huggingface.

I hope this helps.  I would be closing this issue currently. Feel free to reachout if you face any other issues.

<img width="413" alt="Screenshot 2024-09-10 at 1 25 11 PM" src="https://github.com/user-attachments/assets/4dfa7674-f23c-48c9-b0fa-6447f0eba0cd">

**Comment by Arron-Clague** [comment]
HI there : so this is going be a real problem for our langflow deployments : I will certainly look an the Olama options, but initially it looks like we would have to run a whole model structure on the langflow server just to do some embeddings ? Is this really a un-reversable decision ? Is it possible to have some more detail on the technical dependancies issues : in the short term, I can obviously make my own component to wrap the functionality for the hugging space code, and load sentence-transforms manually : but I don't understand the change and why it is removed ?

**Comment by edwinjosechittilappilly** [comment]
Thank you for your message. We were indeed facing some issues with the PyTorch dependencies for HuggingFace local embeddings. To address this, we have provided support using [Hugging Face’s text embeddings inference](https://huggingface.co/docs/text-embeddings-inference). This method can be easily integrated into production environments. For a more efficient approach, please refer to [this guide on running HuggingFace Embeddings locally with CPU](https://huggingface.co/docs/text-embeddings-inference/en/local_cpu).

The change is primarily due to an improvement in how we interact with HuggingFace embeddings. This new method offers a more effective and streamlined approach compared to previous implementations.

If you have further questions about the technical dependencies or need more details, please let us know. In the short term, creating a custom component to wrap the Hugging Face functionality and manually loading sentence-transformers is a viable solution. But I would highly suggest you to try the huggingFace Embeddings Inference component also.

**Comment by edwinjosechittilappilly** [comment]
Hi @Arron-Clague ,

In addition to the Hugging Face support I mentioned earlier, I would also recommend exploring the AstraVectorize component, which supports NVIDIA embeddings as well as several other providers. You can find more details here:

- [AstraVectorize Component Overview](https://docs.datastax.com/en/langflow/components/embeddings.html#astra-db-vectorize)
- [Embedding Generation with Astra DB Serverless](https://docs.datastax.com/en/astra-db-serverless/databases/embedding-generation.html)

The AstraVectorize component provides a flexible and scalable solution for embedding generation, leveraging the power of NVIDIA embeddings and other integrations. This can be a great alternative for your Langflow deployments, especially if you are looking for enhanced performance and support for various embedding providers.

Feel free to explore these resources and see if they fit your needs. If you have any more questions or need further assistance, just let me know!

**Comment by Arron-Clague** [comment]
Hi Edwin : thanks so much for the detailed update : I think I understand where you are going with this : I will definitely check out the AstraDB and HF TEI interfaces. We can definitely close this Issue thread off, and thanks so much for your brilliant answers ! -  Tx Arron
