### ISSUE TITLE
Custom Component Documentation produces errors

### ISSUE THREAD

**Issue by MetricCreativeNola** [langflow-ai/langflow#3732]
### Bug Description

The two sections: Input Types & Generic Inputs generate errors when transferred into langflow for confirmation on standards. 

https://docs.langflow.org/components-custom-components

### Reproduction

1. copy sample code into "custom component"
2. Attempt to save and validate

### Expected behavior

Code should validate if it is an accurate esample of the custom code

### Operating System

Windows 10

### Langflow Version

1.0.17

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/0816d18a-3549-43f7-bbae-0f12fbcceabe)

**Comment by konradbjk** [comment]
I am using docker installation and custom components works (I will explain how) for me. I would check the exact function you are using.

So using the type Component from `langflow.custom` does not work. I went through their code and there seems to be a class problem, where there is a wrong class initialization. Due to this, I just create my custom components from their TextInputComponent, could be any other, depending what you are trying to do.
Sample code: https://github.com/konradbjk/vigilant-memory/blob/master/langflow-custom-components/onboarding_details.py

**Comment by mendonk** [comment]
Thank you for submitting an issue @MetricCreativeNola 

Replacing

```
    def process_inputs(self):
        # Your processing logic here
        return "Processed"
```
with

```
    def process_inputs(self) -> str:
    # Your processing logic here
        return "Processed"
```

will allow the code to validate in Langflow (`-> str:` indicates the method returns a string).

I'm updating this document today, thank you.
