### ISSUE TITLE
Global variables not working properly

### ISSUE THREAD

**Issue by brdebr** [langflow-ai/langflow#3876]
### Bug Description

Hello, I've been testing this project and I'm facing an issue with the global variables not working properly.
For the tests I've done, they save and can be retrieved. But they dont work on many components I've tried.

For example, Ollama model when loading the model list

### Reproduction

To reproduce, just need to set this workflow and press reload on the model list of ollama
If you provide the raw value it works and shows the list, but if you set it as a global variable you see this error when trying to load the list

I'm using langlow with the docker-compose option

![image](https://github.com/user-attachments/assets/24b2b434-8347-4ba2-8584-0404106b1e00)

### Expected behavior

The global variable should work exactly like when setting the raw value

### Operating System

WSL2 - Ubuntu

### Langflow Version

1.0.18

### Python Version

None

### Screenshot

Here you can see an screenshot of the error logs on the langflow container
![image](https://github.com/user-attachments/assets/20935b43-c3e8-4eda-8125-fe25dab79d5c)

**Comment by amibaren** [comment]
the same issue.
it dosen't work correctly, when i set the components(azure openai) configuration with global variables instead of a value.

below is the error message:

Error building Component Azure OpenAI: 1 validation error for MessageTextInput value Value error, Invalid value type <class 'NoneType'> [type=value_error, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.9/v/value_error

**Comment by italojohnny** [comment]
Hey there, how's it going? 
Sorry for taking so long to get back to you. 

Could you explain in more detail how you're defining a global variable to set the model option?
