### ISSUE TITLE
 Loss of Configuration in Composio

### ISSUE THREAD

**Issue by cwgbittencourt** [langflow-ai/langflow#4033]
### Bug Description

I use a Composition tool for GMAIL, where the settings must be in the format selected below:
![image](https://github.com/user-attachments/assets/57edbd09-9404-457b-b594-164e9eda08a6)

Even though the file is saved as shown in the image, when you close Flow and open it again, this configuration is lost, leaving only the first item in the list marked.
![image](https://github.com/user-attachments/assets/d581d009-517d-425d-aa42-49d1e517b4c5)

### Reproduction

I use a Composition tool for GMAIL, where the settings must be in the format selected below:
![image](https://github.com/user-attachments/assets/57edbd09-9404-457b-b594-164e9eda08a6)

Even though the file is saved as shown in the image, when you close Flow and open it again, this configuration is lost, leaving only the first item in the list marked.
![image](https://github.com/user-attachments/assets/d581d009-517d-425d-aa42-49d1e517b4c5)

### Expected behavior

When reopening the flow, the previously chosen settings remain selected.
![image](https://github.com/user-attachments/assets/ea1f8964-01b6-40f8-9eb7-43cdfa3fa38f)

### Operating System

Windows 2011

### Langflow Version

1.0.18

### Python Version

3.11

**Comment by joaoguilhermeS** [comment]
Hi @cwgbittencourt ,

I tested the component and confirmed that this limitation occurs because the inputs are auto-updated after setting your API key. However, if you intend to use it in a production environment, this issue shouldn't arise. You can predefine all the apps you want to use in the component's tweaks:

```json
"ComposioAPI-hW8vx": {
    **"action_names": [
        "GMAIL_ADD_LABEL_TO_EMAIL", 
    ],**
    "api_key": "your_api_key_here",
    "app_names": "GMAIL_CONNECTED",
    "auth_status_config": "GMAIL CONNECTED",
    "entity_id": "default"
},
```

By configuring it this way, you can set the desired apps without the inputs being auto-updated.

Thanks for your contribution, I will contact the team and report what is happening anyway.

**Comment by cwgbittencourt** [comment]
Thanks
