### ISSUE TITLE
Variables don't automatically import when injected via environment variables

### ISSUE THREAD

**Issue by devinbost** [langflow-ai/langflow#4049]
### Bug Description

When importing a flow into a new environment, variables receiving values from environment variables should be propagated automatically to match the behavior of running in backend mode. 
This behavior is important to enable local mirroring of a backend deployment for debugging. 

### Reproduction

1. Create a flow with an Astra component with specific variables (`ASTRA_ENDPOINT,ASTRA_DB_TOKEN`)
2. Export the flow.
3. Create an `.env` file with the variables: `ASTRA_ENDPOINT,ASTRA_DB_TOKEN` (Set them with appropriate values)
4. Start langflow in a clean environment with the following command:
`LANGFLOW_STORE_ENVIRONMENT_VARIABLES=true LANGFLOW_VARIABLES_TO_GET_FROM_ENVIRONMENT=ASTRA_ENDPOINT,ASTRA_DB_TOKEN python -m langflow run --env-file /path/to/.env`
5. Import the flow into a clean deployment (e.g. a different laptop)
6. Notice that fields are empty where variables were set

### Expected behavior

Ideally, the variables would import automatically, and if there is a conflict of values with a variable already set previously, there should be a prompt or warning that the conflicting variable couldn't be set. 
Perhaps this behavior could be enabled/disabled via a toggle. 

When using Kubernetes secrets, I'd expect similar behavior. 

### Operating System

Mac M1 (Apple Silicon)

### Langflow Version

1.0.18

### Python Version

3.10

**Comment by devinbost** [comment]
I believe that's exactly what I'm doing unless I'm missing something.

**Comment by italojohnny** [comment]
Hi Devin, I hope you're doing well!

Your step-by-step guide is spot on, with just one small but crucial detail missing. When exporting your flow, you need to explicitly specify that the flow should be saved with your API Keys.

It’s likely that you didn’t do this because this option only appears when you export the flow from within the canvas. Take a look at the images below:

First, inside the canvas of your flow, click on the flow’s name and then select "export."

![Screenshot 2024-10-09 at 01 31 29](https://github.com/user-attachments/assets/6861be08-3d8f-4b1a-94fb-ac68dd519943)

Second, at this point, a window will appear with an option to include the API Keys along with the flow.

![Screenshot 2024-10-09 at 01 32 01](https://github.com/user-attachments/assets/e5374ab1-9121-41e9-a913-5dc40c112d6e)

Once you do that, your steps should work perfectly. It worked for me!
Please let me know if this worked for you

**Comment by devinbost** [comment]
Hi Italo,

Thank you very much for the help!


I'm actually wondering if there's a solution that doesn't require exporting the keys' values. The reason I don't want to export the key values is I only really want to export the placeholders since the actual key values should be provided at runtime via environment variables. I could set dummy values for the variables in the LangFlow UI before exporting (to prevent leaking the actual key values into the file that will be committed to Github and bundled into a deployment), but then that breaks my ability to test everything locally (since I want the local UI to be able to connect to all the backend services when I run it to test the code before I export the flow for a deployment).
