### ISSUE TITLE
Excessive Debug Logs in recursive_serialize_or_str Function

### ISSUE THREAD

**Issue by dhlidongming** [langflow-ai/langflow#4110]
### Bug Description

I've noticed that the `recursive_serialize_or_str` function in [schema/schema.py](https://github.com/langflow-ai/langflow/blob/d223eccdcc67e929f082352670c629ccf9ccd3fc/src/backend/base/langflow/schema/schema.py#L117)  generates excessive debug-level logs when processing dictionaries with many key-value pairs. This excessive logging leads to increased execution time for some components.
The method performs recursive calls for dictionaries, and when handling strings, it checks for `issubclass(BaseModel)`, which can throw an exception. Although the exception is caught and handled by treating the value as a string, the large number of keys in the dictionary can still result in a significant amount of debug logs being produced.

### Reproduction

1. Create a dictionary with a large number of key-value pairs, or use a component (such as `API Request`) that outputs a large dictionary.
2. Call the `recursive_serialize_or_str` method with this dictionary.
3. Monitor the logs generated during execution.

### Expected behavior

Handle the str type correctly, or ensure that each dictionary generates only one log instead of one for each value.

### Who can help?

@italojohnny @ogabrielluiz

### Operating System

Ubuntu Linux 22.04 

### Langflow Version

1.0.19

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/24d9b3f0-d37c-41db-9994-c3141f3c839b)

**Comment by codenprogressive** [comment]
I would like to report the same issue. The following line of code is issuing the following error: `issubclass() arg 1 must be a class`  https://github.com/langflow-ai/langflow/blob/376e4cfdd3d20d655c3f04cefea474f74f4a5ddc/src/backend/base/langflow/schema/schema.py#L141 

please find a simple flow to reproduce the error:
[reproduce typeerror issubclass.json](https://github.com/user-attachments/files/17356548/reproduce.typeerror.issubclass.json)

screenshot of flow: 
![image](https://github.com/user-attachments/assets/5357cb3e-2943-4b4a-b831-14366e337144)

As highlighted by @dhlidongming, the impact of this bug is signifyingly slowing down the whole flow time execution.

**Comment by ogabrielluiz** [comment]
Hey @dhlidongming 

We made some changes to the logging and that must have passed under the radar. Thanks for the report! 

We'll fix it right away.
