### ISSUE TITLE
Error agent 

### ISSUE THREAD

**Issue by mazierovictor** [langflow-ai/langflow#4119]
### Bug Description

I configured an agent connected to the SearXNG search tool, but when the agent tries to execute a query it displays the error below. The SearXNG link is correct and working! https://searxng-searxng.carfce.easypanel.host/

> Entering new AgentExecutor chain...

Invoking: `brave_search` with `{'query': 'artigo 473 do código de processo civil brasileiro'}`

brave_search is not a valid tool, try one of [searxng_search_tool, calculator].
Invoking: `brave_search` with `{'query': 'art. 473 CPC'}`

[2024-10-11 17:17:35,134][WARNING] Error in callback coroutine: NotImplementedError('AgentAsyncHandler does not implement `on_chat_model_start`')
[2024-10-11 17:19:43,560][WARNING] Error in callback coroutine: NotImplementedError('AgentAsyncHandler does not implement `on_chat_model_start`')
[2024-10-11 17:19:44,355][WARNING] Error in callback coroutine: NotImplementedError('AgentAsyncHandler does not implement `on_chat_model_start`')

### Reproduction

![image](https://github.com/user-attachments/assets/93e9d024-ec20-407a-8495-f9b38aba6d95)

### Expected behavior

I would like to know how to fix the problem, so that the agent can perform the search.

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.0.18

### Python Version

3.10

**Comment by mazierovictor** [comment]
@dosu

Where do I configure the agent?

**Comment by mazierovictor** [comment]
@dosu

I prompted the agent to use searchxng_search_tool and the error still remains.

**Comment by mazierovictor** [comment]
[2024-10-11 18:03:56,646][WARNING] Error in callback coroutine: NotImplementedError('AgentAsyncHandler does not implement `on_chat_model_start`')

**Comment by mazierovictor** [comment]
@dosu

I still have this error, I've tried to change everything, but the agent can't perform the search using SearXNG

[2024-10-11 19:20:41,931][WARNING] Error in callback coroutine: NotImplementedError('AgentAsyncHandler does not implement `on_chat_model_start`')

**Comment by Cristhianzl** [comment]
@mazierovictor hi!

Could you please export and provide your flow's JSON?
It seems like the error is in your Agent code.

I'm using another Agent and is building the flow for me.

![image](https://github.com/user-attachments/assets/76152e0c-d40d-459d-b0ea-48d2451441b1)

**Comment by mazierovictor** [comment]
@Cristhianzl 

So, I switched to the Tool Calling Agent and the flow is assembled, however the agent is not doing the searches correctly and returning inconsistent responses. 

Attached the json.
[Simple Agent.json](https://github.com/user-attachments/files/17347157/Simple.Agent.json)

**Comment by edious** [comment]
> @mazierovictor hi!
> 
> Could you please export and provide your flow JSON? It seems like the error is in your Agent code.
> 
> I'm using another Agent and is building the flow for me.
> 
> ![image](https://private-user-images.githubusercontent.com/72977554/375867400-76152e0c-d40d-459d-b0ea-48d2451441b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjQ0NDAsIm5iZiI6MTcyOTIyNDE0MCwicGF0aCI6Ii83Mjk3NzU1NC8zNzU4Njc0MDAtNzYxNTJlMGMtZDQwZC00NTlkLWIwZWEtNDhkMjQ1MTQ0MWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA0MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZTcwNDY0MjZjYTMxODljNDRhZDU0MGZkZDYzZWMwNWU1MTA4MTg4YTRjYzM4NmZjMDJmZDYyNzg4NTUyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9ApiiKYdsUBPhoVDMXbZ8Xt_IBrJpGXAFiQnTc2HGTQ)

can share this langflow JSON files? I meet the same error. Thanks

**Comment by joaoguilhermeS** [comment]
Hey @mazierovictor,

The issue is that the current search tool, `SearXNG Search Tool,` is throwing errors when your Agent tries to retrieve information. I verified this by testing your Flow. To fix this, I recommend switching to a different search tool for now if possible.

Here are a couple of effective alternatives:

1. **Search Tools**: If you still want to perform direct web searches, you try using Tavily Search, Bing Search API, Search API, etc.

2. **Beautiful Soup Extraction**: If your information can be sourced from specific websites rather than broad searches, Beautiful Soup is an excellent choice for scraping content directly. I developed a tool that leverages Beautiful Soup to streamline data extraction. You can access and integrate it into your project here: [Beautiful Soup Tool on LangFlow](https://www.langflow.store/store/ad22a625-d89a-4333-a007-151473ffb4b2).

An example Flow:
[Ex - Agent with Web Search (1).json](https://github.com/user-attachments/files/17546225/Ex.-.Agent.with.Web.Search.1.json)
