### ISSUE TITLE
No module named xxx when langflow run

### ISSUE THREAD

**Issue by shenshaowei** [langflow-ai/langflow#4241]
### Bug Description

No module named xxx when langflow run
I created a langflow virtual environment in Windows 10 using Anaconda, with Python version 3.12. I activated the environment using anaconda **activate langflow** and installed **langflow** with **`python -m pip install langflow`**.

However, when I input **langflow run** or **python -m langflow run**, I always get the error "No module named xxx."

Please tell me why this is happening. I can see that these modules are listed when I run pip list, and I don't get an error when I run python and import xxx.

Why is this happening?

### Reproduction

No module named xxx when langflow run
I created a langflow virtual environment in Windows 10 using Anaconda, with Python version 3.12. I activated the environment using anaconda **activate langflow** and installed **langflow** with **`python -m pip install langflow`**.

However, when I input **langflow run** or **python -m langflow run**, I always get the error "No module named xxx."

Please tell me why this is happening. I can see that these modules are listed when I run pip list, and I don't get an error when I run python and import xxx.

Why is this happening?

### Expected behavior

run the langflow

### Operating System

win10

### Langflow Version

python -m install langflow

### Python Version

3.12

**Comment by joaoguilhermeS** [comment]
Hey @shenshaowei,

To ensure compatibility with Langflow on Windows 10/11, I recommend installing it using **WSL2**. Some library incompatibilities with Windows can cause errors, and WSL2 helps avoid these issues.

Installing WSL2 allows you to run a Linux kernel within Windows (don't worry, it doesn't consume much processing power). This way, Langflow will run as expected.

For Langflow installation, I suggest using a virtual environment instead of Conda. Use the following commands:

```bash
python3 -m venv env
source env/bin/activate  # For WSL2/Linux
python -m langflow run
```

If you're still using Windows without WSL2, activate the virtual environment with:

```bash
env\Scripts\activate  # For Windows Command Prompt
```
