### ISSUE TITLE
How to delete logs

### ISSUE THREAD

**Issue by Gluepower** [langflow-ai/langflow#4297]
### Bug Description

I have a flow with 1000 logs and logging stopped. How to continue logging for that flow or how to delete old logs so new ones can be created?

### Reproduction

Create 1000 logs, and logging stops 

### Expected behavior

Logging should continue after 1000 logs

### Operating System

Render

### Langflow Version

1.0.19.post2

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/69ec2579-5043-45ce-ac7d-e950c89d6644)

**Comment by joaoguilhermeS** [comment]
Hey @Gluepower, I believe there is not an easy way to do that in Langflow without changing the backend code, since there is not any specific env variable that controls that.

I believe this limit is being set at https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/services/database/models/transactions/crud.py

So if you want to, you can change internally on your deployment to make it work. Fell free to open a feature request issue describing your request.

**Comment by simonstey** [comment]
wouldn't it make sense to just change the default ordering of timestamps to DESC so that it would always show the last 1000 log entries, instead of always the 1000 first logs? 

https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/services/database/models/transactions/crud.py#L20

```python
.order_by(col(TransactionTable.timestamp).desc())
```

**Comment by hd24-jspoerer** [comment]
I like the idea by @simonstey. Should I make a small PR for this change? Should there be a configuration option via an environment variable that allows one to choose between descending (desired implementation) and ascending (current implementation) logs?
