### ISSUE TITLE
does not seem to work with Groq or Ollama

### ISSUE THREAD

**Issue by atanudasgupta** [langflow-ai/langflow#4398]
### Bug Description

the playground freezes trying to use anything other than openAI, is it supported?

### Reproduction

choose model component from the tray, anything other than OpenAI, use one of the default templates, I tried hello world chat

### Expected behavior

it should have worked just like using Openai model

### Operating System

using your cloud hosted version

### Langflow Version

latest

### Python Version

None

**Comment by edwinjosechittilappilly** [comment]
Hi @atanudasgupta,  
Could you please test it in the latest version of Langflow?  
I believe the issue has been resolved.

**Comment by flefevre** [comment]
hello I have tested the nighlty build on docker.
It is now working for Ollama connection but I do not know for Groq.
it will be very nice to look on Litellm also : https://github.com/langflow-ai/langflow/issues/4748 to enable all litellm community to use Langflow.

![image](https://github.com/user-attachments/assets/750c3028-4f49-492a-a60e-97c1d8c588ed)

**Comment by edwinjosechittilappilly** [comment]
Hi,  
<img width="1723" alt="Screenshot 2024-11-22 at 11 00 28 AM" src="https://github.com/user-attachments/assets/c1919625-46bf-4c1f-9b98-1a62f2d9b785">

Thank you for your feedback and testing.  
The issue has been fixed in version 1.1.  I have tested the Groq in the Latest version of langflow.
If you encounter any further issues, please feel free to let us know.
