### ISSUE TITLE
Index_name Confusion of OpenSearch

### ISSUE THREAD

**Issue by songjinu** [langflow-ai/langflow#4422]
The Parallel calls of '/run/{flow_id}' API with different index_name (by tweaks) in OpenSearch: A Test for Index_name Confusion.
when sequencially call API, No prob.
Any one help what the problem? 
(I'm in 1.0.16)

Could We  Parallel calls a same flow_id '/run/{flow_id}' API with many different tweaks ?

**Comment by asilism** [comment]
Hello, I'm a coworker with songjinu.
We have confirmed that this phenomenon only occurs in certain components.

1. A component that has been inherited. 
2. outputs are defined in the parent component
such as , RecursiveCharacterTextSplitterComponent / LCTextSplitterComponent , OpenSearchComponent / LCVectorStoreComponent

I suspect that the cause is **exec_globals** used when **build_custom_class** is called. 
I'm testing deepcopy() outputs in a child class, but I'm not sure if this is the right approach, since the code is so complex.

```python
if exec_globals[class_name].outputs is not None:
            exec_globals[class_name].outputs = copy.deepcopy(exec_globals[class_name].outputs)
```

**Comment by songjinu** [comment]
@joaoguilhermeS, @ogabrielluiz 
Are there good ways to avoid shared The result of outputs in concurrent processing ?

**Comment by joaoguilhermeS** [comment]
Hi @songjinu, I was slightly confused about what you meant, but now I understand. So how does it happen? You can pass different index names during each request you make to your Flow. I just tried it here on the latest version (1.1), and it seems to be working just fine. 

Take a look on these environment variables, this might help you as well: https://docs.langflow.org/environment-variables#LANGFLOW_WORKERS
