### ISSUE TITLE
Error with FirecrawlScrapeApi component in Langflow v1.0.19.post2

### ISSUE THREAD

**Issue by viniciossilva3** [langflow-ai/langflow#4450]
### Bug Description

**[Error with FirecrawlScrapeApi component in Langflow v1.0.19.post2]**

**🌿 Version**

v1.0.19.post2

**🪜 Steps to Reproduce**

1. Add a FirecrawlScrapeApi component in a flow.

2. Execute the component.

**🎯 Expected Behavior**

The FirecrawlScrapeApi component should execute without errors.

**🚧 Actual Behavior**

An error occurs indicating an unexpected keyword argument 'code' in the FirecrawlScrapeApi.build() method.

**💡 Additional Notes**

The error message is as follows: `Error Building Component Error building Component FirecrawlScrapeApi: FirecrawlScrapeApi.build() got an unexpected keyword argument 'code'`.

### Reproduction

1. Add a FirecrawlScrapeApi component in a flow to use the.
2. Execute the component.

### Expected behavior

The FirecrawlScrapeApi component should execute without errors.

### Who can help?

@ogabrielluiz @nicoloboschi

### Operating System

Arch Linux  x86_64 Linux 6.11.2-arch1-1

### Langflow Version

1.0.19.post2

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/fee06b4a-66e5-43b8-9a58-b920832232be)

**Comment by italojohnny** [comment]
The reported error, unexpected keyword argument code, has already been fixed in the latest version of the main branch. However, there are two additional issues:

The Firecrawl API has been updated, along with the extractorOptions and pageOptions parameters. Both Firecrawl components in Langflow are currently outdated.

![Screenshot 2024-11-07 at 13 43 28](https://github.com/user-attachments/assets/5f4d79ba-d896-4a24-891a-74b84648da46)


I'm working on a PR to resolve all these issues.
