### ISSUE TITLE
Out-of-date Component Code detection is intermittent

### ISSUE THREAD

**Issue by mieslep** [langflow-ai/langflow#5179]
### Bug Description

I believe this mostly affects component developers, but not 100% it doesn't affect others. Once a component has been detected as out-of-date and the "Update Component" button is clicked, the component no longer shows as being out-of-date if changes are made, even after restarting services.

### Reproduction

1. Start a development server (`make backend` and `make frontend`)
2. Bring a component onto the canvas
3. Modify that component on the source code; the `backend` service will restart.
4. Refresh the browser; the component will show it needs to be updated.
5. Update the component via the UI.
6. Make another modification to the component; the `backend` service will restart
7. Refresh the browser: the component does ***not*** show it needs to be updated.

### Expected behavior

The component should show it needs to be updated.

### Operating System

devcontainer

### Langflow Version

1.1.1.devX

### Python Version

3.12

**Comment by Cristhianzl** [comment]
hi @mieslep how are you?

I was analyzing your case and noticed that this error occurs when a component's name is changed.
Example: when `name = "ChatInput"` is changed to `name = "ChatInputNew"`

When this happens, we lose the component reference and can no longer update or check if it's outdated because it's interpreted as a component from outside Langflow.
To prevent this error, we ask that you only modify the `display_name` variable. This way, we can detect any code changes and notify users when an update is needed.

Thank you for the feedback.
Please let me know if this works for you.
